    - name: Configurar Conexión Segura con Ngrok
      env:
        NGROK_AUTH_TOKEN: "2ZunC6v3YgGf687Xm9wLQ_2kR1p7v5B4N3M2kL9jH8g"
      run: |
        echo "Instalando Ngrok..."
        choco install ngrok -y
        
        # Autenticar token
        ngrok config add-authtoken "$env:NGROK_AUTH_TOKEN"
        
        echo "Forzando inicio de Sunshine en segundo plano..."
        # Arrancamos el ejecutable de Sunshine directamente para asegurar que escuche el puerto
        Start-Process -FilePath "C:\Program Files\Sunshine\bin\sunshine.exe" -WindowStyle Hidden
        Start-Sleep -Seconds 10
        
        echo "=== INICIANDO TÚNEL TCP EN PUERTO 47990 ==="
        # Ejecutamos Ngrok mostrando la salida en la consola de GitHub para ver la IP directamente
        ngrok tcp 47990 --log=stdout
